-- Configured language servers, external tools, and Tree-sitter parsers.
return {
    servers = {
        "lua_ls",
        "bashls",
        "pyright",
        "rust_analyzer",
        "ts_ls",
        "cssls",
        "html",
        "yamlls",
        "dockerls",
        "clangd",
        "texlab",
        "remark_ls",
        "gopls",
    },
    formatters = {
        "stylua",
        "isort",
        "black",
        "prettier",
        "djlint",
        "clang-format",
        "shellcheck",
        "latexindent",
    },
    parsers = {
        "json",
        "yaml",
        "html",
        "markdown",
        "markdown_inline",
        "bash",
        "lua",
        "vim",
        "vimdoc",
        "dockerfile",
        "gitignore",
        "c",
        "cpp",
        "python",
        "rust",
        "typescript",
        "tsx",
        "javascript",
        "css",
        "go",
    },
}
